spring:
  datasource:
  # añadimos   ?useSSL=false  -->   para que no nos salte el aviso de MySQL ( porque la conexion no es segura )
  # elimino la variable ?useSSL=false , porque sino al añadir la dependencia de spring security casca
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy:  org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  
   # para que no guarde la cache      
  thymeleaf:
    cache: false
  